### ISSUE TITLE
Not really an issue...

### ISSUE THREAD

**Issue by L-30** [Tzwcard/sjrm_rom_ext#1]
Hi!

Hope I can get your attention.
First I'd like to thank you for making this tool to extract Janryumon's BGMs from the ".rom" pack. I am sure it will be very helpful for many of us who have played Janryumon and have a place for it in our hearts.
Now, I am not an expert in coding/programming, so I am not sure what to do with these files in order to extract the ".rom". Would you be willing to explain the steps so I can extract the BGMs out of the file? I would be very grateful.

Thank you!

**Comment by Tzwcard** [comment]
You need to grab and compile zlib, add statically linked library and it's ".h" files into this project file, and compile it.
Then you should see it in "release\" folder, just drag ".rom" files onto it, and that's all.

**Comment by L-30** [comment]
Hi!

So after compiling zlib, linking/adding everything to the project it gave me this error while trying to build:

"LNK2019: unresolved external symbol _uncompress referenced in function "int __cdecl run_extract(char *)" (?run_extract@@YAHPAD@Z)"

I tried it in different versions of Visual Studios as well as using different versions of zlib (even precompiled ones) and everytime I get stuck with this error.

Any ideas on how to workaround this? All I want is the end product tbh, I am bad at this.

Thank you for noticing this.

**Comment by Tzwcard** [comment]
It should just work if you link that lib and just build it tho.
I just dropped a compiled exe in release, maybe you should check that out.
![image](https://user-images.githubusercontent.com/12098388/89937288-7744ae80-dc47-11ea-99d8-bc94d56ee798.png)

**Comment by L-30** [comment]
Hi!

It's weird because I *think* I did properly link everything correctly(path of header in C/C++->General->Additional Include Directories, path of lib Linker->General->Additional Library Directories, and finally the name of lib file in  Linker->Input->Additional Dependencies), but alas, I probably messed up at one point with my lacking knowledge.

Thank you for releasing the .exe, now my adventure is over and my soul in peace.
